export const ACTION_REPLIES = {
  th:{ feed:{ cat:["เหมียวว~","อีก!","พอใช้ได้","นี่ของฉันแล้ว","เมี๊ยว!"], dog:["โฮ่ง!","อีกได้ไหม!","เย้!","อร่อย!","บ๊อกบ๊อก"] }, pet:{ cat:["ครืดด...","ตรงนั้นแหละ","อย่าหยุดนะ","วันนี้ยอมก็ได้"], dog:["ชอบที่สุด!","ลูบอีก!","เย้ เย้!","เป็นเพื่อนกันแล้วนะ"] } },
  en:{ feed:{ cat:["Meowww~","More!","Acceptable.","This is mine now.","Meow!"], dog:["Woof!","Can I have more?","Yay!","Delicious!","Bow-wow!"] }, pet:{ cat:["Purrr...","Right there.","Don't stop.","I'll allow it today."], dog:["My favorite!","More pets!","Yay, yay!","We're best friends now!"] } },
};

export const CHAT_REPLIES = {
  th:{ cat:["เหมียว","เหมียววว~","เมี๊ยว?","เหมียว!","เมี๊ยววว","...เหมียว"], dog:["โฮ่ง!","โฮ่งโฮ่ง!","บ๊อก!","บ๊อกบ๊อก","โฮ่งงง","แฮ่ก ๆ... โฮ่ง!"] },
  en:{ cat:["Meow","Meowww~","Mrrrow?","Meow!","Meeeow","...meow"], dog:["Woof!","Woof woof!","Bark!","Bow-wow!","Woooof","Pant, pant... woof!"] },
};

export const QUESTION_POOLS = {
  cat:[
    { text:"ช่วงนี้น้องจ้องกำแพงนานผิดปกติไหม?", en:"Has your cat been staring at the wall suspiciously long?", answers:[{ text:"ไม่เลย กำแพงยังปลอดภัย", mood:"sleepy", weight:2 },{ text:"บางครั้ง เหมือนกำลังรับสัญญาณ", mood:"domination", weight:2 },{ text:"นานจนกำแพงสารภาพ", mood:"judge", weight:3 }] },
    { text:"ถ้ามีกล่องวางอยู่กลางห้อง น้องทำอะไรเป็นอย่างแรก?", en:"What does your cat do first when a box appears?", answers:[{ text:"เข้าไปทันทีโดยไม่อ่านคู่มือ", mood:"new-home", weight:3 },{ text:"นั่งบนฝากล่อง", mood:"judge", weight:2 },{ text:"วิ่งชนแล้วหายตัว", mood:"energy", weight:3 }] },
    { text:"น้องเคยจ้องคุณเหมือนกำลังตัดสินผลงานหรือไม่?", en:"Does your cat look at you like a performance reviewer?", answers:[{ text:"ทุกวันตอนประเมิน KPI", mood:"judge", weight:3 },{ text:"เฉพาะตอนอาหารช้า", mood:"domination", weight:2 },{ text:"ไม่ น้องหลับอยู่", mood:"sleepy", weight:2 }] },
    { text:"เวลาคุณเรียกชื่อ น้องตอบสนองระดับไหน?", en:"How does your cat respond when called?", answers:[{ text:"หูขยับหนึ่งมิลลิเมตร", mood:"judge", weight:3 },{ text:"เดินมา ถ้ามีค่าตอบแทน", mood:"domination", weight:2 },{ text:"วิ่งมาแล้ววิ่งผ่าน", mood:"energy", weight:3 }] },
    { text:"ช่วงตี 3 น้องกำลังทำอะไร?", en:"What is your cat doing at 3 AM?", answers:[{ text:"วิ่งแข่งกับวิญญาณ", mood:"energy", weight:3 },{ text:"ประชุมลับใต้โต๊ะ", mood:"domination", weight:3 },{ text:"นอนทับหมอนของคุณ", mood:"sleepy", weight:3 }] },
    { text:"เมื่อน้องเห็นพื้นที่ว่างบนชั้นสูง ปฏิกิริยาคือ?", en:"What happens when your cat spots an empty high shelf?", answers:[{ text:"ยึดพื้นที่ทันที", mood:"domination", weight:3 },{ text:"ประเมินมนุษย์ที่วางของขวาง", mood:"judge", weight:2 },{ text:"ปีนขึ้นแล้วหลับ", mood:"sleepy", weight:2 }] },
    { text:"ของชิ้นไหนได้รับอนุญาตให้อยู่ในบ้านมากที่สุด?", en:"Which object is most welcome in your cat's home?", answers:[{ text:"กล่องพัสดุทุกใบ", mood:"new-home", weight:3 },{ text:"ของเล่นที่หายใต้ตู้", mood:"energy", weight:2 },{ text:"เตียงมนุษย์", mood:"sleepy", weight:3 }] },
    { text:"ถ้าถ้วยอาหารว่างก่อนเวลา 4 นาที น้องจะทำอย่างไร?", en:"What if the food bowl is empty four minutes early?", answers:[{ text:"ยื่นคำร้องด้วยเสียงเหมียว", mood:"judge", weight:3 },{ text:"เริ่มแผนโค่นรัฐบาล", mood:"domination", weight:3 },{ text:"ไปนอนรออย่างมีศักดิ์ศรี", mood:"sleepy", weight:2 }] },
  ],
  dog:[
    { text:"ถ้าได้ยินเสียงถุงขนมจากอีกห้อง น้องใช้เวลากี่วินาทีมาถึง?", en:"How fast does your dog arrive after hearing a snack bag?", answers:[{ text:"น้อยกว่าหนึ่ง วิทยาศาสตร์ยังอธิบายไม่ได้", mood:"snack", weight:3 },{ text:"ประมาณสามวินาที", mood:"energy", weight:2 },{ text:"มาถึงก่อนเปิดถุง", mood:"security", weight:2 }] },
    { text:"เวลาเจ้าของกลับบ้าน น้องตื่นเต้นระดับไหน?", en:"How excited is your dog when you come home?", answers:[{ text:"กระดิกหางอย่างสุภาพ", mood:"friend", weight:2 },{ text:"พลังงานเกิน 300%", mood:"energy", weight:3 },{ text:"แจ้งเตือนทั้งหมู่บ้าน", mood:"security", weight:3 }] },
    { text:"ถ้าเห็นคนแปลกหน้า น้องคิดว่าเป็นเพื่อนหรือผู้บุกรุก?", en:"Is a stranger a friend or an intruder?", answers:[{ text:"เพื่อนใหม่แน่นอน", mood:"friend", weight:3 },{ text:"ขอตรวจบัตรก่อน", mood:"security", weight:3 },{ text:"ถ้ามีขนมคือเพื่อน", mood:"snack", weight:2 }] },
    { text:"ของเล่นชิ้นโปรดมีสภาพเหลือกี่เปอร์เซ็นต์?", en:"How much of the favorite toy still exists?", answers:[{ text:"ประมาณ 90% ดูแลดีมาก", mood:"friend", weight:2 },{ text:"เหลือ 12% แต่ยังรักอยู่", mood:"energy", weight:3 },{ text:"เหลือเพียงความทรงจำ", mood:"snack", weight:2 }] },
    { text:"ถ้าคุณพูดคำว่า “ไปเที่ยว” น้องมีปฏิกิริยาอย่างไร?", en:"What happens when you say “go out”?", answers:[{ text:"ยืนรอหน้าประตูแล้ว", mood:"travel", weight:3 },{ text:"คาบสายจูงมารายงานตัว", mood:"security", weight:2 },{ text:"วิ่งเป็นวงกลม 14 รอบ", mood:"energy", weight:3 }] },
    { text:"เมื่อน้องได้กลิ่นอาหารจากระยะไกล ระบบใดทำงานก่อน?", en:"Which system activates first when food is detected far away?", answers:[{ text:"จมูกเรดาร์", mood:"snack", weight:3 },{ text:"หางส่งสัญญาณ", mood:"friend", weight:2 },{ text:"ขาทั้งสี่เปิดโหมดเทอร์โบ", mood:"energy", weight:3 }] },
    { text:"ตอนกลางคืนมีเสียงหน้าบ้าน น้องรับตำแหน่งอะไร?", en:"What job does your dog take when there is a noise outside at night?", answers:[{ text:"หัวหน้าฝ่ายรักษาความปลอดภัย", mood:"security", weight:3 },{ text:"ฝ่ายต้อนรับเพื่อนใหม่", mood:"friend", weight:2 },{ text:"ฝ่ายหลบอยู่หลังเจ้าของ", mood:"travel", weight:2 }] },
    { text:"วันหยุดในฝันของน้องหน้าตาแบบไหน?", en:"What does your dog's dream day off look like?", answers:[{ text:"ออกเที่ยวตั้งแต่เช้า", mood:"travel", weight:3 },{ text:"พบเพื่อนทุกคนในสวน", mood:"friend", weight:3 },{ text:"บุฟเฟต์ขนมไม่จำกัด", mood:"snack", weight:3 }] },
  ],
};

export const EN_ANSWERS = {
  sleepy:["The wall remains safe.","A dignified nap.","Already asleep."], judge:["One-millimeter ear movement.","A formal review is underway.","A complaint has been filed."], domination:["Receiving secret signals.","Compensation may be required.","The takeover plan begins."], "new-home":["Enter immediately; no manual needed.","The box is prime real estate.","Every delivery box."], energy:["Turbo mode activated.","Fourteen victory laps.","Only a memory remains."],
  snack:["Snack radar activated.","Arrived before the bag opened.","Unlimited snack buffet."], friend:["Definitely a new friend.","A very polite tail wag.","Meet everyone at the park."], security:["ID check first.","Notify the entire neighborhood.","Head of Security."], travel:["Waiting at the door already.","Leash ready for inspection.","Adventure starts now."],
};

export const MOODS = {
  cat:{ sleepy:{ title:"วันนี้น้องอยากนอน 23 ชั่วโมง", enTitle:"Your cat wants to sleep for 23 hours", description:"ชั่วโมงที่เหลือมีไว้ย้ายจากเตียงไปนอนในกล่อง", enDescription:"The remaining hour is reserved for moving from the bed into a box.", badge:"Sleep Mode", meter:28, categories:["Beds"] }, judge:{ title:"น้องกำลังตัดสินผลงานมนุษย์", enTitle:"Your cat is reviewing human performance", description:"คะแนนยังไม่ประกาศ แต่การเสิร์ฟอาหารตรงเวลาช่วยได้", enDescription:"Scores are confidential, but serving meals on time may help.", badge:"Human Review", meter:67, categories:["Treats","Accessories"] }, domination:{ title:"แมวของคุณกำลังวางแผนครองโลก", enTitle:"Your cat is plotting world domination", description:"แผนยังเป็นความลับ ของเล่นหนึ่งชิ้นอาจซื้อเวลาให้มนุษยชาติ", enDescription:"The plan is classified. One toy may buy humanity more time.", badge:"Mastermind", meter:94, categories:["Toys"] }, "new-home":{ title:"น้องต้องการกล่องใหม่", enTitle:"Your cat requires a new box", description:"บ้านเดิมยังใช้ได้ แต่มาตรฐานอสังหาฯ ของแมวเปลี่ยนทุกสัปดาห์", enDescription:"The old home works, but feline real-estate standards change weekly.", badge:"Box Hunter", meter:53, categories:["Beds"] }, energy:{ title:"ตรวจพบพลังงานตี 3", enTitle:"3 AM energy detected", description:"เตรียมรับเสียงวิ่งผ่านทางเดินโดยไม่มีต้นเหตุที่ยืนยันได้", enDescription:"Prepare for unexplained hallway sprints.", badge:"3 AM Zoomies", meter:98, categories:["Toys"] } },
  dog:{ friend:{ title:"น้องเชื่อว่าทุกคนคือเพื่อน", enTitle:"Your dog believes everyone is a friend", description:"รวมถึงคนส่งของ เพื่อนบ้าน และใบไม้ที่ปลิวผ่านประตู", enDescription:"Including the courier, the neighbors, and leaves passing the door.", badge:"Best Friend", meter:78, categories:["Accessories"] }, snack:{ title:"ระบบตรวจจับขนมทำงานจากระยะไกล", enTitle:"Long-range snack detection is online", description:"ความแม่นยำสูงกว่าเรดาร์และเปิดใช้งานตลอด 24 ชั่วโมง", enDescription:"More accurate than radar and active around the clock.", badge:"Snack Radar", meter:88, categories:["Treats"] }, energy:{ title:"พลังงานเกิน 300%", enTitle:"Energy level exceeds 300%", description:"ควรปล่อยพลังอย่างเป็นระบบก่อนโซฟาจะรับหน้าที่แทน", enDescription:"Release it safely before the sofa volunteers.", badge:"Turbo Mode", meter:100, categories:["Toys"] }, travel:{ title:"น้องต้องการออกเที่ยวเดี๋ยวนี้", enTitle:"Your dog needs an adventure right now", description:"สายจูงพร้อม หางพร้อม เหลือเพียงมนุษย์ที่ยังใส่รองเท้าไม่เสร็จ", enDescription:"Leash ready, tail ready; only the human is still putting on shoes.", badge:"Adventure Now", meter:85, categories:["Accessories"] }, security:{ title:"น้องคือหัวหน้าฝ่ายรักษาความปลอดภัย", enTitle:"Your dog is Head of Security", description:"ทุกเสียงต้องผ่านการตรวจสอบ แม้กระทั่งเสียงตู้เย็น", enDescription:"Every sound requires inspection, including the refrigerator.", badge:"Security Chief", meter:72, categories:["Accessories"] } },
};
